---
- name: Install Varnish.
  apt: name=varnish state=installed

- name: Copy Varnish configuration.
  template:
    src: varnish.service.j2
    dest: /lib/systemd/system/varnish.service
    owner: root
    group: root
    mode: 0644
